### ISSUE TITLE
iotile build hitting character limit

### ISSUE THREAD

**Issue by x24ling** [iotile/coretools#278]
Sometimes hits the issue: "The command line is too long."

Solution is to put commands into a file and run it.

**Comment by x24ling** [comment]
Ended up using this guy's code:

https://bitbucket.org/scons/scons/wiki/LongCmdLinesOnWin32

**Comment by timburke** [comment]
@x24ling This is done now correct and can be closed?

**Comment by x24ling** [comment]
I believe this is resolved, closing now.
