### ISSUE TITLE
Add set_device_template command to iotile_ext_cloud

### ISSUE THREAD

**Issue by timburke** [iotile/coretools#337]
There needs to be a function:

```
def set_device_template(self, device_id, template_name, os_tag=None):
    """Sets the device template for the given device in iotile.cloud.
        
        Is os_tag is passed, verify that the device template explicitly matches
        the expected os_tag by making another API call.
    """
```

added to `IOTileCloud` in `iotile-ext-cloud`

@dkarchmer What API is this a patch on?

**Comment by timburke** [comment]
It should go in this file:
https://github.com/iotile/coretools/blob/master/iotile_ext_cloud/iotile/cloud/cloud.py#L85

**Comment by dkarchmer** [comment]
I wonder if the API should also confirm that the os_tag matches that template_name. If so, you will want to check from:

https://iotile.cloud/api/v1/dt/pod-1gg1-v3-0-1/

But the API to patch is the same one as the sensor graph

PATCH: /api/v1/device
```
payload = {
    'template': 'slug'
}
```

**Comment by timburke** [comment]
I would say we should add an optional argument that takes an `os_tag` and if given explicitly verifies it before patching and raises if it doesn't match.

**Comment by dkarchmer** [comment]
May want to do the same on the old sensor_graph as well, and pass an optional app_tag

**Comment by timburke** [comment]
Yup, agreed.  So to confirm there are now two parts of this:

- [ ] Add a new `set_device_template` function that take a device_id, a template name and optional `os_tag`
- [ ] Modify `set_sensorgraph` to take an optional `app_tag` and explicitly verify that if passed.

**Comment by x24ling** [comment]
What's the best way to test these functions? It seems like currently there are tests to use a mock cloud.

The way i'm currently acquiring tags asscociated with the values is this way, but i always get a return where 'Authentication credentials were not provided'.
sg_os_tag = requests.get('https://iotile.cloud/api/v1/dt/%s/' % (new_template)).json().get('os_tag', None)

I also wrote test_set_sensorgraph, but it doesn't seem to be passing with the current mock cloud, is there something i should be setting? I'll be creating a pr to show you what i mean.

**Comment by x24ling** [comment]
nvmd, i just found a good reference in test_check_time()

**Comment by timburke** [comment]
The `mock_cloud` may need to be modified to allow for patching the relevant APIs.  I don't believe it has support for that right now.  The `mock_cloud` implementation is here:

https://github.com/iotile/python_iotile_cloud/blob/master/iotile_cloud/utils/mock_cloud.py#L192

You can see an example of how we support handling a POST and the default GET there.  You may need to modify the `device` API to add support for a PATCH.

**Comment by dkarchmer** [comment]
See my comments on PR. Never use `requests.get('https://iotile.cloud/api/v1/...'`. Instead use `self.api` instead
