### ISSUE TITLE
Add support for creating bootstrap images in iotile-build

### ISSUE THREAD

**Issue by timburke** [iotile/coretools#350]
There should be a way to combine multiple elfs into a single bootstrap `.hex` file.

The functionality should live in:
https://github.com/iotile/coretools/blob/master/iotilebuild/iotile/build/config/site_scons/autobuild.py

There should be a new function like:

```python
def autobuild_bootstrap_file(file_name, image_list):
    """Combine multiple firmware images into a single bootstrap hex file."""
```

All of the files in image_list should be assumed to live in `build/output` and `file_name` should be generated in that folder as well.  You can look at `autobuild_release` for examples of how to set up the scons environment for building:

https://github.com/iotile/coretools/blob/master/iotilebuild/iotile/build/config/site_scons/autobuild.py#L104

**Comment by x24ling** [comment]
Closed by PR #354
