### ISSUE TITLE
Breaking compatibilities since new Tornado version 5

### ISSUE THREAD

**Issue by haroal** [iotile/coretools#389]
Tornado release its new version 5.0 on March 5th. This new version introduces multiple breaking compatibilities with the previous version we used (4.4.0). A temporary fix was to restrict the version of Tornado used (cf commit c864bea).

We should update our code to use the new Tornado v5.

[Travis logs of a build which failed due to this bug](https://travis-ci.org/iotile/coretools/builds/350125893)

Errors which occurred were:

1.
```
>  tornado.ioloop.PeriodicCallback(self.device_expiry_callback, 1000, self._loop).start()
E  TypeError: __init__() takes exactly 3 arguments (4 given)
../.tox/py27/lib/python2.7/site-packages/iotilegateway/device.py:46: TypeError
```

Documentation ref: http://www.tornadoweb.org/en/stable/releases/v5.0.0.html#tornado-ioloop

2.

```
Traceback (most recent call last):
  File "/home/travis/build/iotile/coretools/.tox/py27/lib/python2.7/site-packages/iotilegateway/supervisor/supervisor.py", line 85, in run
    server = HTTPServer(app, io_loop=self.loop)
  File "/home/travis/build/iotile/coretools/.tox/py27/lib/python2.7/site-packages/tornado/util.py", line 312, in __new__
    instance.initialize(*args, **init_kwargs)
TypeError: initialize() got an unexpected keyword argument 'io_loop'
```

Documentation ref: http://www.tornadoweb.org/en/stable/releases/v5.0.0.html#tornado-process

**Comment by timburke** [comment]
This fix is merged into master now and will be releases at `iotile-gateway` `v1.5.2`
