### ISSUE TITLE
Add `watch` and `watch_reports` to HardwareManager

### ISSUE THREAD

**Issue by timburke** [iotile/coretools#445]
There should be a way to just have `iotile` print out newly received scan information with a filter and to print out each new report as it comes in for debugging purposes.

### Example Usage

Should print every newly broadcast reading from a specific device
`iotile hw watch --uuid 0x100 --only-readings`

Should block until Ctrl-C and print information about every new report received from a device as it comes in.
`iotile hw watch_reports --include-streams=[0x5001, 0x5002]`

**Comment by timburke** [comment]
A variable of this has been implemented for watching broadcast reports that can provide a template for watching realtime streams.  It uses the `asciimatics` package to provide a console based ui that lets you update the values for each stream in place.

https://github.com/iotile/coretools/blob/master/iotilecore/iotile/core/hw/hwmanager.py#L438

**Comment by timburke** [comment]
The remaining work to be done here is to implement `watch_reports` which is invokable after connecting to a device and supports the following arguments:

- whitelist_streams: list of int, if given will only show those streams
- blacklist_streams: list of int, if given will show all streams other than those specific

By default all streams from the device will be shown.

**Comment by mattrunchey** [comment]
@timburke Is the functionality described in this issue implemented with #510 ?

**Comment by timburke** [comment]
Yes it is 👍
