### ISSUE TITLE
Add device_slug to scan payload

### ISSUE THREAD

**Issue by dkarchmer** [iotile/coretools#530]
I only find myself having to find a HEX to INT converter to convert my device slug into a UUID so I can find it in the **scan** results.

Does it make sense to add 

```
"slug": "d--......"  (or "device_slug" or "device_id", or "s/n")
```

to the scan payload results?

**Comment by timburke** [comment]
I'm on board with this.  We should add it to `HardwareManager.scan()` to patch in a `slug` field based on the `uuid` field of the scan data received:

https://github.com/iotile/coretools/blob/master/iotilecore/iotile/core/hw/hwmanager.py#L857
