### ISSUE TITLE
Fix all remaining instances of `xrange` for python 3 compatibility

### ISSUE THREAD

**Issue by timburke** [iotile/coretools#567]
https://github.com/iotile/coretools/search?q=xrange&type=Code

**Comment by mattrunchey** [comment]
Another thing to fix along the same lines is to replace all Queue imports with try/except:
```
try:
  import Queue
except:
  import queue
```
https://stackoverflow.com/questions/29687837/queue-importerror-in-python-3/29688081#29688081

**Comment by timburke** [comment]
Agreed with the intent but python-future backfills this so you just always
do the from `queue import Queue` on python 2 and 3>

**Comment by mattrunchey** [comment]
Oh, cool. Yea looks like just switching the import to lowercase works on both out of the box, much easier than the try/except.

**Comment by timburke** [comment]
This has new priority now that we're python 3 only.  There are 2 packages that still have `xrange` references, `iotile-test` and `iotile-transport-jlink`

**Comment by timburke** [comment]
This has been fixed now in the latest master.
