### ISSUE TITLE
Continue using `object` as base class of all classes

### ISSUE THREAD

**Issue by timburke** [iotile/coretools#595]
Per the discussion at https://github.com/iotile/coretools/pull/510#discussion_r219591646 it seemed that we could stop using `object` as a base class for all classes since that was the default behavior on python 2.7 and above.

However, that does not appear to be case.  In particular, `super` does not work on python 2 if classes do not inherit from `object`.

```
Traceback (most recent call last):
  File "C:\Arch\python_multipackage\workspace\env2\Scripts\multipackage-script.py", line 11, in <module>
    load_entry_point('multipackage', 'console_scripts', 'multipackage')()
  File "c:\arch\python_multipackage\multipackage\scripts\multipackage.py", line 291, in main
    retval = verify_repo(args.repo)
  File "c:\arch\python_multipackage\multipackage\scripts\multipackage.py", line 141, in verify_repo
    repo = create_repo(repo_path)
  File "c:\arch\python_multipackage\multipackage\scripts\multipackage.py", line 102, in create_repo
    return Repository(repo_path)
  File "c:\arch\python_multipackage\multipackage\repo.py", line 84, in __init__
    self.template = PyPIPackageTemplate()
  File "c:\arch\python_multipackage\multipackage\templates\pypi_package.py", line 16, in __init__
    super(PyPIPackageTemplate, self).__init__()
TypeError: super() argument 1 must be type, not classobj
```

So, we need to keep inheriting explicitly from `object` in order to be able to use `super` on Python 2.7.

@mattrunchey

**Comment by mattrunchey** [comment]
Ah, interesting. There seems to be another option where the class using super can inherit from object (https://stackoverflow.com/a/18392639/4647944). However, that seems like a bit of overimplementation to just avoid pylint complaints (and more code change if many other classes inherit from an objectless base class).

Should we patch this on an as-needed basis, or blanket apply `object` to every base class that isn't new style?

**Comment by timburke** [comment]
@mattrunchey It was an unrelated update from the `iotile/multipackage` repository where I was experimenting with not inheriting from `object` on all of my classes.  I would personally recommend we just keep inheriting everything from `object` on new classes and update the `.pylintrc` to disable that message on python 3 rather than disabling the python 2 message about old-style classes.  

We already inherit everthing from object throughout the codebase so it shouldn't require any major work.

**Comment by mattrunchey** [comment]
Now that we're on Py3, we can drop object where it still exists as we find it.
