### ISSUE TITLE
Chatty log message in bled112 transport plugin

### ISSUE THREAD

**Issue by timburke** [iotile/coretools#615]
When viewing the log from a bled112 connection there is a chatty message that comes up a fair number of times and looks like a development message that isn't needed anymore:

```
19-01-09 09:40:31.599 INF iotile_transport_bled112.bled112_cmd Num events in _write_handle: 1
19-01-09 09:40:31.638 INF iotile_transport_bled112.bled112_cmd Num events in _write_handle: 1
```

**Comment by mattrunchey** [comment]
This was fixed in https://github.com/iotile/coretools/pull/653
