### ISSUE TITLE
past.builtins very slow to import, move off of it

### ISSUE THREAD

**Issue by timburke** [iotile/coretools#647]
My general philosophy has been to avoid it whenever possible and rely on the `future` package to cleanly handle any required backports.  In general that has worked quite well, with the only exception being what I discovered with `past.builtins` over the weekend.  

I did import profiling using [import_profiler](https://github.com/cournape/import-profiler) and found that just importing `past.builtins` caused 100-200 ms delay in the startup time of the iotile tool because apparently that module is implemented by calling `2-to-3` at import time to analyze some code and dynamically generate the module in some way.  

Ideally, we would just blacklist `past.builtins` and find a way to never need it but I have not found a cleaner alternative yet.  The only use-case we have for it is when we need to check if something is a string in order to trigger string conversion to some type when we could also receive the type directly.  In that case we need something like a `isinstance(x, str)` but that breaks on python 2 since depending on where the string came from it could be `str` or `unicode`.  However, unicode doesn't exist on python 3.  So the workaround we settled on was `isinstance(x, basestring)` with the `past.builtins` port for python 3.  However, now it looks like that is super slow to import so we may need to write a utility module to check for strings that has a python 2 / python 3 branch inside and replace all basestring usage with that.

There could be an `iotile.core.utilities` routine for this that we use through CoreTools and then blacklist the `past.builtins` module.

**Comment by timburke** [comment]
@mattrunchey Did your cleanup of `from past.builtins import basestring` remove all of the references to `past.builtins` from the codebase?  If so we can close this issue.

**Comment by mattrunchey** [comment]
I only explicitly looked for `past.builtins` and only in two packages, `core` and `test`. Still TBD to find the rest of them. Last search only showed a few other references, though - https://github.com/iotile/coretools/search?q=past.builtins&unscoped_q=past.builtins

**Comment by mattrunchey** [comment]
Done
