### ISSUE TITLE
no audit log messages for virtual device

### ISSUE THREAD

**Issue by JKHeadley** [iotile/coretools#661]
Following the tutorial:
https://coretools.readthedocs.io/en/latest/tutorials.html#using-virtual-device

I'm able to connect to the virtual device, however no audit log messages appear.

![screen shot 2019-02-04 at 8 40 43 am](https://user-images.githubusercontent.com/12631935/52222570-a6ab7b80-2858-11e9-9837-7513fd3e1c01.png)

![screen shot 2019-02-04 at 8 40 30 am](https://user-images.githubusercontent.com/12631935/52222568-a57a4e80-2858-11e9-82f1-8c46b8f9e5ef.png)

**Comment by mattrunchey** [comment]
If you pass "-vv" (to turn the log level to INF) to the `virtual_device` command, you will see audit log messages. They don't look perfectly like the tutorial ones, but:
```
51.235 INF virtual.audit The device streamed a report to the client, report=IOTile Report (length: 20, visible readings: 1, visible events: 0, not verified and not encrypted)
```

We can amend the tutorial to include this.

**Comment by timburke** [comment]
Closing this as expected.  We may want to update the tutorial to reflect the current actual output from the `virtual_device` script.
