### ISSUE TITLE
rpc_v2 does not appear to validate its arguments

### ISSUE THREAD

**Issue by timburke** [iotile/coretools#676]
I accidentally configured an RPC in a way that should fail but it didn't, it silently sent just a partial result.

I had code like the following:

```
error, = self.rpc_v2(0x8091, "BB12s", "L", index, int(force), result.encode())
```

However, `result.encode()` produced a 15-byte encoded value.  There should have been an exception saying that the arguments could not be encoded properly.  There was no exception and it's not clear what was sent but I assume it was the first 12-bytes of the 15-byte value.

Similarly, I had a previous example where I forgot to append an argument and the RPC still worked but sent nothing:

```
self.rpc_v2(0xAAAA, "L", "")
```

This should fail because it takes 1 argument for the "L" and not are provided but it appears to succeed silently.  In case it matters this was on python 3 but I don't think that it is the issue.

**Comment by mattrunchey** [comment]
I wrote some tests to figure out how this would behave differently between the original rpc and rpc_v2, but currently don't see either validate that the exception is raised. Snippets of my test rpc and response:

```
    def test_invalid_rpc_v1(self):

        error, = self.rpc(0x80, 0x91, 1, 2, bytes(15), arg_format="BB12s", result_format="L")
        return error

    def test_invalid_rpc_v2(self):
        error, = self.rpc_v2(0x8091, "BB12s", "L", 1, 2, bytes(15))
        return error
```

And the implementation of the RPC i'm calling:
```

    @tile_rpc(0x8091, "BB12s", "L")
    def foo(self, a, b, c):
        return [1]
```

In both cases, my caller just prints out 1:
```

    res = p.test_invalid_rpc_v1()
    print(res)
    res = p.test_invalid_rpc_v2()
    print(res)
```

I tried a similar approach where rpc_v2 didn't send the proper arguments but got an appriate error message raised on both:

```

    def test_invalid_args_rpc_v1(self):
        error, = self.rpc(0xaa, 0xaa, arg_format="L", result_format="")
        return

    def test_invalid_args_rpc_v2(self):
        error, = self.rpc_v2(0xaaaa, "L", "")
        return

```

The definition of the RPC as
```
    @tile_rpc(0xaaaa, "L", "")
    def bar(self, a):
        return []
```

And in both cases I can invoke an error by calling the rpc, though they are different:
v1
```
pack expected 1 items for packing (got 0)
```
v2
```
*** EXCEPTION OCCURRED IN RPC ***
Traceback (most recent call last):
  File "/Users/mrunchey/gitrepos/coretools/iotilecore/iotile/core/hw/virtual/common_types.py", line 148, in _rpc_executor
    args = unpack_rpc_payload(arg_format, payload)
  File "/Users/mrunchey/gitrepos/coretools/iotilecore/iotile/core/hw/virtual/common_types.py", line 111, in unpack_rpc_payload
    return struct.unpack(code, payload)
struct.error: unpack requires a buffer of 4 bytes
```

**Comment by timburke** [comment]
@mattrunchey It looks like the first issue is present on both `rpc` and `rpc_v2` then.  I wonder if there is behavior in `struct.pack` that we didn't understand that will silently take a prefix of a bytes object if it is longer than the format specifier asks for.  Yep, from `struct.pack`:

```
For the 's' format character, the count is interpreted as the size of the string, not a repeat count like for the other format characters; for example, '10s' means a single 10-byte string, while '10c' means 10 characters. If a count is not given, it defaults to 1. For packing, the string is truncated or padded with null bytes as appropriate to make it fit. For unpacking, the resulting string always has exactly the specified number of bytes. As a special case, '0s' means a single, empty string (while '0c' means 0 characters).
```

https://docs.python.org/2/library/struct.html

It looks like we are going to need to check for this condition ourselves before passing data to `struct.pack` if we want to fix it.  

For the second issue, I think the `v2` version would not throw that error if it were being called with a non-virtual transport plugin.  That exception is coming from the rpc implementation itself, not from the `rpc_v2` method checking its arguments before invoking the RPC.  On a real device over `ble`, that checking would not happen automatically unless the C implementation of the RPC did a length check on its arguments, which not all of them do.

**Comment by mattrunchey** [comment]
Is there any reason to not move `rpc` to use `pack_rpc_payload` and `unpack_rpc_payload`?

I tested out a validator to raise an exception on truncation, but would like to port `rpc` to also call that function if it's given an arg_format:

```

    code = _create_respcode(arg_format, args)

    packed_result = struct.pack(code, *args)
    unpacked_validation = struct.unpack(code, packed_result)
    if tuple(args) != unpacked_validation:
        raise RPCInvalidArgumentsError("Passed values would be truncated, please validate the size of your string",
                                       code=code, args=args)

    return packed_result
```

**Comment by timburke** [comment]
@mattrunchey I agree in principle that we should move `rpc` to use that as well.  My hesitation is just around breaking some tile's proxy somewhere with an edge case that's currently hard to test until we happen to call that RPC.  My recommendation would be to file an issue that we should backport this to `rpc`, make the fix in `rpc_v2` and we should just always use `rpc_v2` in new proxies anyway so we should always benefit from the fix in new code.

**Comment by mattrunchey** [comment]
I did fix the issue with rpc_v2 not validating arguments as well. Will submit a PR once we decide if we also want to include validating arg packing as mentioned above.

**Comment by mattrunchey** [comment]
Filed tracking issue for the V1 limitation #679 and PR to address the rpc_v2 regression.
