### ISSUE TITLE
Prepare for major version upgrade

### ISSUE THREAD

**Issue by mattrunchey** [iotile/coretools#690]
We are introducing some Python3-only behavior that will break our compatibility with Python 2, and will need to complete a major version upgrade of all packages in that work.

Before that, we need to modify all current packages to not auto upgrade by pinning their coretools dependencies to `==` instead of `>=`.

We should also make sure all of our third-party dependencies also don't rely on non-stuck versions, or at least set a cap for the ones that plan to drop py2 support in future (i.e. how we load `tornado` -- toornado<=5.0.0;>4.0.0).

**Comment by mattrunchey** [comment]
Branch `py2.7` will serve as a record of the "last" py2 compatible release of coretools packages.

There were a *couple* of small fixes after that which I may cherry-pick over to the branch for the record.

As of now, the latest coretools packages are marked py3.5+ only (and <py4, for when that comes out)

**Comment by timburke** [comment]
This has been merged and released now.
