### ISSUE TITLE
Add ability to flash firmware blob to bled112 dongles using coretools

### ISSUE THREAD

**Issue by timothyfroehlich** [iotile/coretools#846]
At @ekkizogloy 's request, this should remove a significant amount of work that's currently being done manually.

The goal will be to run a python script that finds all bled112's and updates them. Will be using the transport-bled112 libraries as much as possible and the flashing code will likely need to live in `bled112_cmd.py`. I may see if I can integrate it into the main iotile code path (so you can do something like `iotile hw --port=bled112 install-blob --blob='file'`) But if it's non-trivial I'll just stick with the script.

Questions for @timburke:
Has this been attempted before? Is there anything I should know before I start? I've found the spec for how it should work.

What's going on with bled112_cmd.py and bled112_cmd.co.py? Which one should I use / modify? Both? I'm not familiar with asyncio yet (though I intend to learn soon) so I'd be more comfortable modifying the original.

**Comment by timburke** [comment]
It is going to be very nontrivial to integrate this into `iotile` so I would just stick with a script.  You can bundle it with the `iotile-transport-bled112` package if you want as a `bled112-update-firmware` script.  

However, if you do that, you should not add any additional dependency requirements to the overall package requirements.  If additional dependencies are needed you should check for them in the script and tell the user to install them manually.  Most people using `iotile-transport-bled112` won't need to use the script so adding another installation dependency isn't warranted.

**Comment by timburke** [comment]
`bled112_cmd.py` is fine to modify.  There was a partial port to support asyncio natively that is used when emulating a POD using `virtual-device`.  `bled112_cmd.py` is still used for client connections to PODs.

**Comment by timothyfroehlich** [comment]
Sounds good. I'm not expecting to need any extra dependencies.

**Comment by timburke** [comment]
Hmm, okay.  I'm surprised if you don't need a `libusb` dependency but maybe not.  I was always assuming the bled112 rebooted into USB DFU compatible mode for a firmware update and then you sent the blob using DFU.

**Comment by timburke** [comment]
Nope, you're right.  It looks like it's all done over vcom:
![image](https://user-images.githubusercontent.com/2424759/60367754-e14ab780-99a3-11e9-9711-6144f2868b52.png)

**Comment by timothyfroehlich** [comment]
Yep, exactly.

**Comment by timothyfroehlich** [comment]
Well, maybe scratch all that? https://www.silabs.com/community/wireless/bluetooth/knowledge-base.entry.html/2015/08/06/_reference_updatin-Rtcr

```
DFU over USB - INSTRUCTIONS HERE - (only on BLE112 and BLED112, since the BLE113 has no USB)
 

DFU over UART (only on BLE112/BLE113/BLE121LR, since the BLED112 has no exposed UART)
```

It implies that the only way to update it is via USB, but I'm not sure, the Windows tool seems like it sees it as a COM device, but maybe it just uses that to select one and determine the USB address? It also seems to imply that the BLED112 doesn't have UART at all, but that's how we communicate with it... Unless the blob adds a UART?

@x24ling Where did the blob (https://github.com/iotile/coretools/tree/master/transport_plugins/bled112/blob) originally come from?

**Comment by timburke** [comment]
We built the blob but I'm pretty sure the process for the update is:
- command is sent over USB (virtual com port) to restart the chip into DFU usb mode
- the chip resets and shows up as a different usb class device (dfu class rather than cdc vcom class)
- the windows tool pushes the firmware using the usb standard dfu protocol.

Getting around using the windows tool would require having a dfu-protocol capable tool, for example [this one](https://github.com/vpelletier/python-dfu)

**Comment by timothyfroehlich** [comment]
Yeah, that's what it's looking like. The instructions that we have for flashing the blobs use the "USB Bootloader" tab instead of the "UART Bootloader" tab. I tried the UART upload, and it does reboot the device but the upload doesn't work. Going to keep reading what I can (I don't really want to just start experimenting and bricking them) but the tool you linked looks promising.

**Comment by timothyfroehlich** [comment]
@x24ling @timburke @ekkizogloy Just realized... I don't know how to know whether the flashing worked, other than the GUI flasher saying "finished" or being able to connect to Pods with it. Is there some method I can use to identify whether they've worked or not? The data from `lsusb -v` doesn't seem to change.

**Comment by timburke** [comment]
The only thing the flashing changes is allowing the BLED112 to **be connectable** like a POD.  So the way to test it is to run `virtual-device bled112 reference_1_0` and verify you can connect to it from another bled112 dongle using `iotile hw connect 1` which is the default uuid.

To be clear, you don't need to flash the dongle in order to connect to a POD, the only use of flashing is to allow the dongle to act like a pod itself.

**Comment by timothyfroehlich** [comment]
sounds good. I also found the info command in the Bluegiga gui which reports a build number of 140.

**Comment by timothyfroehlich** [comment]
Ok, I've managed to do a working flash using dfu-utils. Unfortunately, @timburke, the python code you linked is still python 2 and doesn't seem to be detecting the device anyways. . I found another code base that's Python3 (https://github.com/madcowswe/ODrive/blob/master/tools/odrive/dfu.py) , but it's integrated into their code, not standalone, and I don't know how much of it is custom to their device. Since I can just do the flash via a shell command I'm thinking it'll be simplest to just do that. We can flash the dongles using the production PC in the green room. Thoughts?

**Comment by timothyfroehlich** [comment]
Need to do cleanup and review, but I've got bled112s flashing at about 4 every 8 seconds. The script when run will flash every bled it finds on the system. Suggested workflow is to fill a USB hub with bled's, plug it in, start the flasher, then fill a second USB hub. Once the first is finished, swap the two and continue. Linux only, but that's what the Production PC is for. Need to finish cleanup and send through review. I could potentially make it faster by setting it up to flash in parallel, but I suspect that's overkill, you'll be bottlenecked by emptying and refilling the hubs (Though more than one person working on it at once will probably remove that bottleneck)

**Comment by timothyfroehlich** [comment]
@ekkizogloy @x24ling

**Comment by ekkizogloy** [comment]
Omg... so great
