### ISSUE TITLE
[iotile-build] Upgrade to scons-local-3.0.3 to comply with python 3

### ISSUE THREAD

**Issue by x24ling** [iotile/coretools#860]
Scons recently updated its code to comply with python 3.X

I personally ran into this issue when running iotile-build to build firmware on windows. Differences occured in theses lines:

Current scons 3.0.3:
https://github.com/SCons/scons/blob/fe8e5013e9c0a313efe97c9eb55dc8f050ac5e0a/src/engine/SCons/Platform/win32.py#L88-L90

Our local scons 3.0.1:
https://github.com/iotile/coretools/blob/28bb8579327aaef61422b0e9045ded605b2d6cb2/iotilebuild/iotile/build/config/scons-local-3.0.1/SCons/Platform/win32.py#L82-L92

And error I received was:
```
UnsupportedOperation: fileno:
  File "C:\Users\chris\iotile\con_btc1\con_nrf52832\SConstruct", line 5:
    autobuild.autobuild_arm_program(elfname, patch=False)

....

  File "c:\users\chris\iotile\env\new_prod_workspace\lib\site-packages\entrypoints.py", line 156:
    fu = io.TextIOWrapper(f)
  File "c:\users\chris\iotile\env\new_prod_workspace\lib\site-packages\iotile\build\config\scons-local-3.0.1\SCons\Platform\win32.py", line 90:
    win32api.SetHandleInformation(msvcrt.get_osfhandle(self.fileno()),
```

https://github.com/SCons/scons

**Comment by x24ling** [comment]
With scons-3.0.1 on my windows machine, call `pytest iotilebuild/test` gives the test outputs:
test_iotilebuild\test_scons.py .........FF..Fs..

Fails `test_build_arm`, `test_build_arm_defines`, `test_build_prerelease`

Passes the tests after scons is bumped to 3.0.3

**Comment by mattrunchey** [comment]
@x24ling I'm closing this with the assumption that the PR resolved.
