### ISSUE TITLE
Add support for bundling data file with support wheels

### ISSUE THREAD

**Issue by timburke** [iotile/coretools#866]
When `iotile-build` generates support wheels, it needs to check for the presence of non `.py` files indicating that data files are being bundled and generate the appropriate `setup.py` statements to include those files.

The files need to be accessible both when the component is installed in dev mode (`iotile registry add_component <PATH>`) as well as when the component pip installed.

All of the python wheel building happens in this file:
https://github.com/iotile/coretools/blob/master/iotilebuild/iotile/build/config/site_scons/pythondist.py

The end result of this issue should be that:
- if a module has a `support_package` product, then the folder containing the support package can contain non-python data files.  If this happens the built wheel will bundle those data files.

**Comment by anwu** [comment]
Closed with https://github.com/iotile/coretools/pull/868
