### ISSUE TITLE
Test failure, multiple controller support packages not processing properly

### ISSUE THREAD

**Issue by mattrunchey** [iotile/coretools#887]
## Repro steps

From a new virtualenv, I installed `iotilecore` locally (so I could add print statements), and then installed
```
pip install iotile-support-con-nrf52832-4
pip install iotile-support-con-nrf52832-3
pip install iotile-support-lib-controller-4
pip install iotile-support-lib-controller-3
```

Then, you can get in to the iotile command utility with the refcn1:
```
iotile -vvvvv hw --port="emulated:reference_1_0" 
```

In there, type in :
```
connect 1
get 8 --force='NRF52 '
```

This prompts the output:
```
(HardwareManager) get 8 --force='NRF52 '
19-10-23 12:37:40.746 DEB iotile.core.hw.hwmanager Short name matched proxies found: [<class 'iotile_support_con_nrf52832_3.nrf52832_controller.NRF52832Controller'>, <class 'iotile_support_con_nrf52832_4.nrf52832_controller.NRF52832Controller'>]
19-10-23 12:37:40.746 DEB iotile.core.hw.hwmanager Found a proxy without ModuleVersion info: <class 'iotile_support_con_nrf52832_3.nrf52832_controller.NRF52832Controller'>
19-10-23 12:37:40.746 DEB iotile.core.hw.hwmanager Best proxy found: <class 'iotile_support_con_nrf52832_3.nrf52832_controller.NRF52832Controller'> with base version 0.0.0
DataError: Could not find proxy plugin module in registered components or installed distributions
Additional Information:
name: SensorGraphPlugin
component: iotile_standard_library/lib_controller
```

We do properly select the con_nrf52832_3 package, but don't seen to also select an appropriate lib_controller one? Maybe we didn't fully path out selecting the right lib_controller thing?

**Comment by anwu** [comment]
Fixed.

Last release of `iotile-support-lib-controller-3` was not meant to include `ReferenceControllerProxy`. Somehow that commit with that new features got merged into that last `3.x` release.

I went ahead and reverted that commit and re-released `iotile-support-lib-controller-3` as `3.8.2` with the revert fix.
