### ISSUE TITLE
iotile-ship's recipe_manager doesn't seem to support adding recipe resources from modules

### ISSUE THREAD

**Issue by timothyfroehlich** [iotile/coretools#947]
See: https://github.com/iotile/coretools/blob/d1ab27a0cdedf8659c179b29b36ebc7ab5f7aa72/iotileship/iotile/ship/recipe_manager.py#L28

While it'll load recipe actions from modules (it loads `build_steps`) it doesn't support loading resources from modules. It only loads resources from entry_points, which as far as I know a module can't create.

@timburke If you think this is fine then I'll make the modifications and submit a PR.

**Comment by timburke** [comment]
That seems fine to me.  

The place you'll want to edit in iotilebuild is here (in addition to changes in iotile-ship itself to match the behavior you call out above with `recipe_action`:
https://github.com/iotile/coretools/blob/d1ab27a0cdedf8659c179b29b36ebc7ab5f7aa72/iotilebuild/iotile/build/config/site_scons/pythondist.py#L18

**Comment by timothyfroehlich** [comment]
Merged in #948
