### ISSUE TITLE
Audit codebase for any direct python-iotile-cloud `Api` usage and ensure it respects verify=False

### ISSUE THREAD

**Issue by timburke** [iotile/coretools#953]
We need to verify that we have found all of our direct use of the `Api` object in CoreTools and are not missing any places that need to updated to support `self-signed` TLS certificates.

**Comment by timburke** [comment]
Here are the places that we found during an initial nonexhaustive search:

https://github.com/iotile/coretools/blob/master/iotile_ext_cloud/iotile/cloud/cloud.py#L51
https://github.com/iotile/coretools/blob/master/iotile_ext_cloud/iotile/cloud/config.py#L54

**Comment by dvksirin** [comment]
It seems `Api` class in `coretools` repo is only used in two places mentioned above.
One more place should be updated to support self-signed certificates:
https://github.com/iotile/coretools/blob/master/iotile_ext_cloud/iotile/cloud/apps/ota_updater.py#L31

**Comment by timburke** [comment]
Got it, understood.
