### ISSUE TITLE
[iotile-build] breathe/sphinx dependency fix

### ISSUE THREAD

**Issue by x24ling** [iotile/coretools#967]
On april 7th, `breathe` recently upgraded to 4.15.0, which now depends on `sphinx` 3.0.0.
https://github.com/michaeljones/breathe/commits/master

According to our setup requirements, our dependencies break this:
https://github.com/iotile/coretools/blob/123f46a6b6d93e62903fad3ef64f54379e620ca3/iotilebuild/setup.py#L29-L41

We need to either
1. Force `breathe` to stick to 4.14.1
2. Bump `sphinx` to `>=3,<4",`

**Comment by timburke** [comment]
@x24ling I would just pin breathe for now and then we can update later.

**Comment by x24ling** [comment]
cool, i'll take care of this
